config/routes.rb
Rails.application.routes.draw do
  resources :about, only: %i[index]
  resources :cards, only: %i[index show] do
    collection do
      get "search"
    end
  end
  root to: "home#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord
  has_many :monster_cards
  has_many :card_prices
  has_many :card_sellers, through: :card_prices

  validates :name, :card_type, :description, :race, :card_image, :card_image_small, presence: true
  validates :name, uniqueness: true

  paginates_per 20

  def markers_list
    monster_cards.first.markers.map(&:marker_direction).join(", ")
  end
end

app/models/card_price.rb
class CardPrice < ApplicationRecord
  belongs_to :card
  belongs_to :card_seller
  validates :price, presence: true
end

app/models/card_seller.rb
class CardSeller < ApplicationRecord
  has_many :card_prices
  has_many :cards, through: :card_prices
  validates :seller_name, presence: true, uniqueness: true

end

app/models/link_marker.rb
class LinkMarker < ApplicationRecord
  belongs_to :monster_card
  belongs_to :marker
end

app/models/marker.rb
class Marker < ApplicationRecord
  has_many :link_markers
  has_many :monster_cards, through: :link_markers
  validates :marker_direction, presence: true, uniqueness: true
end

app/models/monster_card.rb
class MonsterCard < ApplicationRecord
  belongs_to :card
  has_many :link_markers
  has_many :markers, through: :link_markers

  validates :attack, :defense, :level, :link_value, :scale, numericality: {only_integer: true}
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  def index
    @cards = Card.page params[:page]
    @monsters = MonsterCard.includes(:card).all
  end
  #The @cards variable will be shared with:
  #app/views/cards/index.html.erb
  #NOTE other models can be called and shared to this view as well

  # <ul>
  #   <% @monsters.each do |monster| %>
  #     <li><%= monster.card.name %> has an atk of <%= monster.attack %></li>
  #   <% end %>
  # </ul>

  def show
    @card = Card.find(params[:id])
    @monster = MonsterCard.where(card_id: params[:id]).first
    @monsters = MonsterCard.includes(:card).all
    @sellers = Card.find(params[:id]).card_sellers
  end
  #The @card variable will be shared with:
  #app/views/cards/show.html.erb

  def search
    wildcard_search = "%#{params[:keywords]}%"
    @cards = Card.where("name LIKE ?", wildcard_search)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @cards = Card.order('RANDOM()').limit(10)
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/about/index.html.erb
<h1>About Page</h1>
 <div class="row">
    <div class="col-sm">
      <h2>Details About My Data Source.</h2>
      <p>I grew up playing Yu-Gi-Oh and watching the anime as a kid and played for fun in 2002-2004. It was not till
      2010 when I picked up the game again and really got into it learning the rules, keeping up with the meta, and
      learning what all the cards did. I was fortunate enough to find this very well put together dataset source so I opted
      to use it for my midterm project to build my first Ruby on Rails application.</p>

      <p>This dataset is came as a json api which I then store locally and created a relational database around. It lists out 10,000
      plus cards with their name, type, stats, price from multiple sellers, which sets they were released in and so much more.
      This dataset was put together by a team of developers at YGOPRODeck who who have their own site and app as well so please support them
      by checking out their links below!</p>

      <h3>YGOPRODeck Contacts:</h3>
        <div><a href="https://db.ygoprodeck.com/">Website</a></div>
        <div><a href="https://twitter.com/YGOPRODeck">Twitter</a></div>
        <div><a href="https://discord.com/invite/AZwvGpa">Discord</a></div>
        <div><a href="https://github.com/AlanOC91/YGOPRODeck/issues">GitHub</a></div>
        <div><a href="https://db.ygoprodeck.com/api/v7/cardinfo.php">Yu-Gi-Oh! API</a></div>
        <div><a href="https://db.ygoprodeck.com/api-guide/">Yu-Gi-Oh! API Guide</a></div>


    </div>
  </div>

app/views/cards/index.html.erb
<div>
  <h2 class="mb-3">YU-GI-OH Card Listing</h2>

  <ul class="list-group ">
    <% @cards[1..150].each do |card| %>
      <li>
        <div class="row mb-3">
          <div class="col-sm-12 col-md-6 col-lg-3">
            <a href="<%= card_path(card) %>"><img class="img-fluid" src="<%= card.card_image_small %>" alt="<%= card.name %>"></a>
          </div>
          <div class="col-sm-12 col-md-6 col-lg-9">
            <h4><strong>Name:</strong> <%= link_to card.name, card %></h4>
            <p><strong>Card Type:</strong> <em><%= card.card_type %></em></p>
            <p><strong>Card Sub Type:</strong> <em><%= card.race %></em></p>
          </div>
        </div>
      </li>
    <% end %>
  </ul>
  <%= paginate @cards%>
</div>

app/views/cards/search.html.erb
<p class="mb-5">Found <%= pluralize(@cards.count, 'Card') %> when searching for: <%= params[:keywords] %></p>

<ul>
  <% @cards.each do |card|%>
    <li><%= link_to card.name, card %></li>
  <% end %>
</ul>

app/views/cards/show.html.erb
<%# Determines if our card is monster %>
<% if @card.card_type.include?("Monster")%>

  <div class="row mb-3">
    <%# Card image %>
    <div class="col-sm-12 col-md-4 col-lg-5">
      <img class="mb-3 img-fluid" src="<%= @card.card_image %>" alt="<%= @card.name %>">
    </div>

    <%# Determines if the monster is Pendulum %>
    <% if @card.card_type.include?("Pendulum") %>
      <div class="col-sm-12 col-md-4 col-lg-4 set_border">
        <h4><strong>Card Details</strong></h4>
        <h5><strong>Name:</strong> <em><%= @card.name %></em></h5>
        <h5><strong>Level:</strong> <em><%= @card.monster_cards.first.level %></em></h5>
        <h5><strong>Card Type:</strong> <em><%= @card.card_type %></em></h5>
        <h5><strong>Attribute:</strong> <em><%= @card.monster_cards.first.monster_attribute %></em></h5>
        <h5><strong>Stats: ATK/</strong><em><%= @card.monster_cards.first.attack %></em> <strong>DEF/</strong><em><%= @card.monster_cards.first.defense %></em></h5>
        <h5><strong>Scales:</strong> <em><%= @card.monster_cards.first.scale %></em></h5>
        <h5><strong>Effect/Description:</strong> <em><%= @card.description %></em></h5>
        <% if !(@card.archetype.nil?)%>
          <h5><strong>Archetype:</strong> <em><%= @card.archetype %></em></h5>
        <% end %>
      </div>
    <%# Determines if the monster is Link %>
    <% elsif @card.card_type.include?("Link") %>
      <div class="col-sm-12 col-md-4 col-lg-4 set_border">
        <h4><strong>Card Details</strong></h4>
        <h5><strong>Name:</strong> <em><%= @card.name %></em></h5>
        <h5><strong>Card Type:</strong> <em><%= @card.card_type %></em></h5>
        <h5><strong>Attribute:</strong> <em><%= @card.monster_cards.first.monster_attribute %></em></h5>
        <h5><strong>Stats: ATK/</strong><em><%= @card.monster_cards.first.attack %></em></h5>
        <h5><strong>Link:</strong> <em><%= @card.markers_list %></em></h5>
        <%# This is where all Link directions will go when model is complete %>
        <h5><strong>Link Arrows:</strong> <em><%= @card.monster_cards.first.link_value %></em></h5>
        <h5><strong>Effect/Description:</strong> <em><%= @card.description %></em></h5>
        <% if !(@card.archetype.nil?)%>
          <h5><strong>Archetype:</strong> <em><%= @card.archetype %></em></h5>
        <% end %>
      </div>
    <%# Otherwise can be any other monster category %>
    <% else %>
      <div class="col-sm-12 col-md-4 col-lg-4 set_border">
        <h4><strong>Card Details</strong></h4>
        <h5><strong>Name:</strong> <em><%= @card.name %></em></h5>
        <h5><strong>Level:</strong> <em><%= @card.monster_cards.first.level %></em></h5>
        <h5><strong>Card Type:</strong> <em><%= @card.card_type %></em></h5>
        <h5><strong>Attribute:</strong> <em><%= @card.monster_cards.first.monster_attribute %></em></h5>
        <h5><strong>Stats: ATK/</strong><em><%= @card.monster_cards.first.attack %></em> <strong>DEF/</strong><em><%= @card.monster_cards.first.defense %></em></h5>
        <h5><strong>Effect/Description:</strong> <em><%= @card.description %></em></h5>
        <% if !(@card.archetype.nil?)%>
          <h5><strong>Archetype:</strong> <em><%= @card.archetype %></em></h5>
        <% end %>
      </div>
    <% end %>


    <div class="col-sm-12 col-md-4 col-lg-3 set_border">
    <%# This will be implemented when card price models are created %>
      <h4><strong>Card Prices</strong></h4>
      <h5><strong>Lowest Listing By Seller:</strong></h5>
      <p><strong>Note: If price is $0.00 card is unavailable on that site</strong></p>
      <%# Takes our list of sellers and creates a 2D array along with the associated prices %>
      <% x = @sellers%>
      <% y = @card.card_prices%>
      <% z = x.zip(y)%>

      <%# Itterates through our 2D array to give us the display %>
      <% z.each do |seller, cost|%>
        <h5><strong><%= seller.seller_name %></strong>: $<em><%= cost.price %></em></h5>
      <% end %>
    </div>

  </div>

<%# if not a monster it is either Spell, trap or Skill card %>
<% else %>

  <div class="row">
    <%# Card image %>
    <div class="col-sm-12 col-md-4 col-lg-5">
      <img class="mb-3 img-fluid" src="<%= @card.card_image %>" alt="<%= @card.name %>">
    </div>

    <%# Card attributes %>
    <div class="col-sm-12 col-md-4 col-lg-4 set_border">
      <h4><strong>Card Details</strong></h4>
      <h5><strong>Name:</strong> <em><%= @card.name %></em></h5>
      <h5><strong>Card Type:</strong> <em><%= @card.card_type %></em></h5>
      <h5><strong>Effect/Description:</strong> <em><%= @card.description %></em></h5>
      <% if !(@card.archetype.nil?)%>
        <h5><strong>Archetype:</strong> <em><%= @card.archetype %></em></h5>
      <% end %>
    </div>

    <%# Card prices based on set and rarity %>
    <div class="col-sm-12 col-md-4 col-lg-3 set_border">
    <%# This will be implemented when card price models are created %>
      <h4><strong>Card Prices</strong></h4>
      <h5><strong>Lowest Listing By Seller:</strong></h5>
      <p><strong>Note: If price is $0.00 card is unavailable on that site</strong></p>
      <%# Takes our list of sellers and creates a 2D array along with the associated prices %>
      <% x = @sellers%>
      <% y = @card.card_prices%>
      <% z = x.zip(y)%>

      <%# Itterates through our 2D array to give us the display %>
      <% z.each do |seller, cost|%>
        <h5><strong><%= seller.seller_name %></strong>: $<em><%= cost.price %></em></h5>
      <% end %>
    </div>
  </div>
<% end %>

app/views/home/index.html.erb
<h1>All Things Yu-Gi-Oh!</h1>
<div class="row">
  <div class="col-sm">
    <h2>10 Random Yu-Gi-Oh Cards!</h2>

    <% @cards.each do |card| %>
      <div>
        <div class="row mb-3">
          <div class="col-sm-12 col-md-6 col-lg-3">
            <a href="<%= card_path(card) %>"><img class="img-fluid" src="<%= card.card_image_small %>" alt="<%= card.name %>"></a>
          </div>
          <div class="col-sm-12 col-md-6 col-lg-9">
            <h4><strong>Name:</strong> <%= link_to card.name, card %></h4>
            <p><strong>Card Type:</strong> <em><%= card.card_type %></em></p>
            <p><strong>Card Sub Type:</strong> <em><%= card.race %></em></p>
          </div>
        </div>
      </div>
    <% end %>
  </div>

  <div class="col-sm">
    <h2>Videos on How to Get Started in Yu-Gi-Oh!</h2>
    <ol>
      <li><a href="https://www.youtube.com/watch?v=55gsu3_36Fs&ab_channel=Cimoooooooo">How to Play Yu-Gi-Oh in 3 Minutes!</a></li>
      <li><a href="https://www.youtube.com/watch?v=l_Xj_xMVmAw&ab_channel=TeamAPS">Things Every New Player Should Do!</a></li>
      <li><a href="https://www.youtube.com/watch?v=s1QsMX9MwHA&ab_channel=Cimoooooooo">Detailed How to Play Yu-Gi-Oh!</a></li>
      <li><a href="https://www.youtube.com/watch?v=Ji5Y0V3o_ys&ab_channel=Cimoooooooo">Turn Structure in Yu-Gi-Oh!</a></li>
      <li><a href="https://www.youtube.com/watch?v=zw2NBRKNMhg&ab_channel=Cimoooooooo">Normal Summoning, Sets, and Tribute Summoning in Yu-Gi-Oh!</a></li>
      <li><a href="https://www.youtube.com/watch?v=Jv04D1nDzeM&ab_channel=Cimoooooooo">Flip Summoning and Special Summoning in Yu-Gi-Oh!</a></li>
      <li><a href="https://www.youtube.com/watch?v=_avm719bV2w&ab_channel=Cimoooooooo">Fusion Summoning in Yu-Gi-Oh!</a></li>
      <li><a href="https://www.youtube.com/watch?v=PVHp60pNtow&ab_channel=Cimoooooooo">Ritual Summoning in Yu-Gi-Oh!</a></li>
      <li><a href="https://www.youtube.com/watch?v=vWFRf_eq42o&ab_channel=Cimoooooooo">Synchro Summoning in Yu-Gi-Oh!</a></li>
      <li><a href="https://www.youtube.com/watch?v=mNZrQAB1HcU&ab_channel=Cimoooooooo">XYZ Summoning in Yu-Gi-Oh!</a></li>
      <li><a href="https://www.youtube.com/watch?v=5BBrXaX-qp4&ab_channel=Cimoooooooo">Link Summoning in Yu-Gi-Oh!</a></li>
      <li><a href="https://www.youtube.com/watch?v=NLQhwBKm86A&t=1s&ab_channel=Cimoooooooo">Pendulum Summoning in Yu-Gi-Oh!</a></li>
    </ol>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Yugioh On Rails</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark ">
        <a class="navbar-brand" href="/">All Things Yu-Gi-Oh!</a>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item active">
              <a class="nav-link" href="/cards">Cards</a>
            </li>
            <%# <li class="nav-item active">
              <a class="nav-link" href="#">Card Price Listings</a>
            </li> %>
            <li class="nav-item active">
              <a class="nav-link" href="/about">About</a>
            </li>
          </ul>

          <%= form_with(url: search_cards_path, method: :get, local: true) do %>
            <div class="form-inline my-2 my-lg-0">
              <div class="control is-expanded">
                <%= text_field_tag(:keywords, nil, class: "input form-control mr-sm-2", placeholder: 'Search for Cards') %>
              </div>
              <div class="control">
                <%= submit_tag("Search", class: "btn btn-outline-success my-2 my-sm-0")%>
              </div>
            </div>
          <% end %>
        </div>
      </nav>
      <%= yield %>
    </div>
  </body>
</html>